name = "ars-api"
main = "src/index.ts"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "ars.cactus.watch", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "ars-mcp-db"
database_id = "dbdadb9d-6ae9-4a6b-b7b0-3de9aaec8f8b"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "ARSMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ARSMCP"]

[vars]
SITE_NAME = "Arizona Revised Statutes"
